### ISSUE TITLE
Folder BLAST_databases does not exist when building database

### ISSUE THREAD

**Issue by heleensev** [X-lab-3D/PANDORA#221]
When rebuilding the database:

```
from PANDORA.Database import Database

db = Database.Database()
db.construct_database(n_jobs=32)
```

the following command in the execution failed:

`mkdir /gpfs/home1/severin/software/PANDORA/Databases/default/BLAST_databases/templates_blast_db`

This is because the folder `BLAST_databases` did not exist yet in my `PANDORA/Databases` folder
Manually creating this folder resolved the issue.

**Comment by DarioMarzella** [comment]
Hi @heleensev , this is happening because you are trying to generate the database after having installed pandora from a older commit.
If you normally download and install, the pip installation (and, when released, conda) will take care of creating all the necessary folders.
Otherwise you have to update them manually.

**Comment by DarioMarzella** [comment]
We could add the feature of checking the presence, and eventually create the folders when the database is being generated. Normal users should never encounter this error, but we might still add the feature just to be sure.
